// Equipment slots and catalog for duel modifiers and armoury loadouts.

export const GEAR_SLOTS = {
  head: { id: "head", label: "Headwear", icon: "🤠", placeholder: "No hat equipped" },
  chest: { id: "chest", label: "Outfit / Armor", icon: "🧥", placeholder: "No chest armor equipped" },
  weapon: { id: "weapon", label: "Weapon", icon: "🗡️", placeholder: "No weapon equipped" },
  accessory: { id: "accessory", label: "Accessory / Boots", icon: "👢", placeholder: "No boots or spurs equipped" },
};

export const GEAR_ITEMS = {
  // Headwear
  straw_sombrero: {
    id: "straw_sombrero",
    name: "Straw Sombrero",
    slot: "head",
    icon: "👒",
    tier: 1,
    stats: { hp: 15 },
    statLabels: ["+15 Max HP"],
    recipe: { wheat: 6, leather: 1 },
    description: "Lightweight sun protection that keeps your head cool in duels.",
    sellPrice: 20,
    levelRequired: 1,
    upgrades: null,
  },
  bandit_bandana: {
    id: "bandit_bandana",
    name: "Bandit Bandana",
    slot: "head",
    icon: "🧣",
    tier: 2,
    stats: { crit: 0.05, attack: 1 },
    statLabels: ["+5% Crit Chance", "+1 Attack Dmg"],
    recipe: { leather: 8, gold: 5 },
    description: "Intimidates rivals and sharpens your aiming eye.",
    sellPrice: 50,
    levelRequired: 3,
    upgrades: "straw_sombrero",
  },
  sheriff_hat: {
    id: "sheriff_hat",
    name: "Sheriff's Stetson",
    slot: "head",
    icon: "🤠",
    tier: 3,
    stats: { hp: 25, crit: 0.05, attack: 2 },
    statLabels: ["+25 Max HP", "+5% Crit Chance", "+2 Attack Dmg"],
    recipe: { leather: 15, gold: 12, wood: 8 },
    description: "The mark of frontier authority. Imposing presence and deadly focus.",
    sellPrice: 120,
    levelRequired: 5,
    upgrades: "bandit_bandana",
  },

  warlord_helm: {
    id: "warlord_helm",
    name: "Warlord Helm",
    slot: "head",
    icon: "⛑️",
    tier: 4,
    stats: { hp: 50, crit: 0.08, attack: 4 },
    statLabels: ["+50 Max HP", "+8% Crit Chance", "+4 Attack Dmg"],
    recipe: { leather: 30, gold: 28, wood: 20, wheat: 15 },
    description: "Hammered gold-reinforced helm worn by those who survived every frontier war.",
    sellPrice: 380,
    levelRequired: 10,
    upgrades: "sheriff_hat",
  },
  phantom_crown: {
    id: "phantom_crown",
    name: "Phantom Crown",
    slot: "head",
    icon: "👑",
    tier: 5,
    stats: { hp: 90, crit: 0.12, attack: 7 },
    statLabels: ["+90 Max HP", "+12% Crit Chance", "+7 Attack Dmg"],
    recipe: { leather: 60, gold: 55, wood: 45, wheat: 30 },
    description: "Forged from nightmare metal. Only legends who have never lost wear it.",
    sellPrice: 1200,
    levelRequired: 15,
    upgrades: "warlord_helm",
  },

  // Chest / Armor
  serape_poncho: {
    id: "serape_poncho",
    name: "Serape Poncho",
    slot: "chest",
    icon: "🪡",
    tier: 1,
    stats: { block: 2, hp: 10 },
    statLabels: ["-2 Block Dmg taken", "+10 Max HP"],
    recipe: { wheat: 8, wood: 2 },
    description: "Woven wool cushion that dampens incoming blows.",
    sellPrice: 25,
    levelRequired: 1,
    upgrades: null,
  },
  leather_vest: {
    id: "leather_vest",
    name: "Hardened Leather Vest",
    slot: "chest",
    icon: "🦺",
    tier: 2,
    stats: { hp: 20, block: 3 },
    statLabels: ["+20 Max HP", "-3 Block Dmg taken"],
    recipe: { leather: 10, wood: 6 },
    description: "Tough cattle hide that absorbs heavy impacts.",
    sellPrice: 65,
    levelRequired: 3,
    upgrades: "serape_poncho",
  },
  outlaw_duster: {
    id: "outlaw_duster",
    name: "Outlaw Trench Duster",
    slot: "chest",
    icon: "🧥",
    tier: 3,
    stats: { hp: 35, block: 4, crit: 0.05 },
    statLabels: ["+35 Max HP", "-4 Block Dmg taken", "+5% Crit Chance"],
    recipe: { leather: 18, gold: 15 },
    description: "Legendary heavy leather duster favored by the quickest guns.",
    sellPrice: 150,
    levelRequired: 5,
    upgrades: "leather_vest",
  },

  iron_brigandine: {
    id: "iron_brigandine",
    name: "Iron Brigandine",
    slot: "chest",
    icon: "🛡️",
    tier: 4,
    stats: { hp: 65, block: 7, crit: 0.07 },
    statLabels: ["+65 Max HP", "-7 Block Dmg taken", "+7% Crit Chance"],
    recipe: { leather: 35, gold: 30, wood: 20, wheat: 15 },
    description: "Layered iron-studded armour built for siege survivors.",
    sellPrice: 420,
    levelRequired: 10,
    upgrades: "outlaw_duster",
  },
  shadow_mantle: {
    id: "shadow_mantle",
    name: "Shadow Mantle",
    slot: "chest",
    icon: "🌑",
    tier: 5,
    stats: { hp: 110, block: 12, crit: 0.10 },
    statLabels: ["+110 Max HP", "-12 Block Dmg taken", "+10% Crit Chance"],
    recipe: { leather: 65, gold: 60, wood: 45, wheat: 35 },
    description: "Absorbs darkness itself. Near-impenetrable at close range.",
    sellPrice: 1400,
    levelRequired: 15,
    upgrades: "iron_brigandine",
  },

  // Weapons
  rusty_machete: {
    id: "rusty_machete",
    name: "Cane Machete",
    slot: "weapon",
    icon: "🗡️",
    tier: 1,
    stats: { attack: 2 },
    statLabels: ["+2 Attack Dmg"],
    recipe: { wood: 5, gold: 1 },
    description: "Forged from timber handle and sharpened gold-alloy blade.",
    sellPrice: 20,
    levelRequired: 1,
    upgrades: null,
  },
  six_shooter: {
    id: "six_shooter",
    name: "Six-Shooter Revolver",
    slot: "weapon",
    icon: "🔫",
    tier: 2,
    stats: { attack: 4, crit: 0.05 },
    statLabels: ["+4 Attack Dmg", "+5% Crit Chance"],
    recipe: { wood: 12, gold: 10 },
    description: "A trusty frontier sidearm with crisp trigger pull.",
    sellPrice: 70,
    levelRequired: 3,
    upgrades: "rusty_machete",
  },
  gold_peacemaker: {
    id: "gold_peacemaker",
    name: "Gold Peacemaker",
    slot: "weapon",
    icon: "✨",
    tier: 3,
    stats: { attack: 7, crit: 0.10 },
    statLabels: ["+7 Attack Dmg", "+10% Crit Chance"],
    recipe: { wood: 18, gold: 22 },
    description: "Masterwork revolver delivering devastating stopping power.",
    sellPrice: 160,
    levelRequired: 5,
    upgrades: "six_shooter",
  },

  thunder_spire: {
    id: "thunder_spire",
    name: "Thunder Spire",
    slot: "weapon",
    icon: "⚡",
    tier: 4,
    stats: { attack: 12, crit: 0.10 },
    statLabels: ["+12 Attack Dmg", "+10% Crit Chance"],
    recipe: { wood: 25, gold: 22, leather: 15, wheat: 10 },
    description: "A weapon that cracks the air itself on impact.",
    sellPrice: 450,
    levelRequired: 10,
    upgrades: "gold_peacemaker",
  },
  void_blade: {
    id: "void_blade",
    name: "Void Blade",
    slot: "weapon",
    icon: "🌑",
    tier: 5,
    stats: { attack: 20, crit: 0.15 },
    statLabels: ["+20 Attack Dmg", "+15% Crit Chance"],
    recipe: { wood: 40, gold: 35, leather: 25, wheat: 20 },
    description: "Cuts through everything, even space.",
    sellPrice: 1500,
    levelRequired: 15,
    upgrades: "thunder_spire",
  },

  // Accessory / Boots
  riding_boots: {
    id: "riding_boots",
    name: "Riding Boots",
    slot: "accessory",
    icon: "👢",
    tier: 1,
    stats: { hp: 10, exp: 0.10 },
    statLabels: ["+10 Max HP", "+10% EXP Gain"],
    recipe: { leather: 3, wood: 3 },
    description: "Sturdy leather boots that keep your footing balanced.",
    sellPrice: 30,
    levelRequired: 1,
    upgrades: null,
  },
  silver_spurs: {
    id: "silver_spurs",
    name: "Silver Spurs",
    slot: "accessory",
    icon: "⭐",
    tier: 2,
    stats: { exp: 0.20, crit: 0.05 },
    statLabels: ["+20% EXP Gain", "+5% Crit Chance"],
    recipe: { leather: 10, gold: 8 },
    description: "Jingling spurs that bring flair and swift reflexes.",
    sellPrice: 75,
    levelRequired: 3,
    upgrades: "riding_boots",
  },
  lucky_horseshoe: {
    id: "lucky_horseshoe",
    name: "Golden Horseshoe",
    slot: "accessory",
    icon: "🧲",
    tier: 3,
    stats: { coinBonus: 0.15, crit: 0.08, hp: 15 },
    statLabels: ["+15% Wager Profit", "+8% Crit Chance", "+15 Max HP"],
    recipe: { gold: 18, leather: 8 },
    description: "Brings exceptional fortune in wagers and lethal shootouts.",
    sellPrice: 150,
    levelRequired: 5,
    upgrades: "silver_spurs",
  },
  eclipse_spurs: {
    id: "eclipse_spurs",
    name: "Eclipse Spurs",
    slot: "accessory",
    icon: "☀️",
    tier: 4,
    stats: { exp: 0.30, crit: 0.10, hp: 25 },
    statLabels: ["+30% EXP Gain", "+10% Crit Chance", "+25 Max HP"],
    recipe: { leather: 30, gold: 20, wood: 15 },
    description: "Spurs forged during a solar eclipse.",
    sellPrice: 400,
    levelRequired: 10,
    upgrades: "lucky_horseshoe",
  },
  mythic_hooves: {
    id: "mythic_hooves",
    name: "Mythic Hooves",
    slot: "accessory",
    icon: "🐎",
    tier: 5,
    stats: { exp: 0.50, crit: 0.15, coinBonus: 0.25, hp: 40 },
    statLabels: ["+50% EXP Gain", "+15% Crit Chance", "+25% Wager Profit", "+40 Max HP"],
    recipe: { leather: 50, gold: 40, wood: 30, wheat: 25 },
    description: "Legends say they carry you to destiny.",
    sellPrice: 1300,
    levelRequired: 15,
    upgrades: "eclipse_spurs",
  },
};

export const GEAR_LIST = Object.values(GEAR_ITEMS);
